apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ namespace }}
  labels:
    run: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx-deployment
  template:
    metadata:
      labels:
        run: nginx-deployment
    spec:
      containers:
      - image: nginx:{{ app_version }}
        name: nginx-deployment
        ports:
        - containerPort: 80
          protocol: TCP

